export { default as MainLayout } from './main-layout/MainLayout'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Main } from './main/Main'
export { default as ResponsiveLayout } from './responsive-layout/ResponsiveLayout'